[package]
name = "tree-sitter-stack-graphs-solidity"
version = "0.1.0"
description = "Stack graphs definition for Solidity using tree-sitter-solidity"
readme = "README.md"
keywords = ["tree-sitter", "stack-graphs", "solidity"]
authors = [
    "Joran Honig",
]
license = "MIT"
edition = "2018"

[[bin]]
name = "tree-sitter-stack-graphs-solidity"
path = "rust/bin.rs"
required-features = ["cli"]

[lib]
path = "rust/lib.rs"
test = false

[[test]]
name = "test"
path = "rust/test.rs"
harness = false

[features]
cli = ["anyhow", "clap", "tree-sitter-stack-graphs/cli"]

[dependencies]
anyhow = { version = "1.0", optional = true }
clap = { version = "4", optional = true, features = ["derive"] }
tree-sitter-stack-graphs = { version = "0.8.1" }
tree-sitter-solidity = "^1.2.2"

[dev-dependencies]
anyhow = "1.0"
tree-sitter-stack-graphs = { version = "0.8.1", features = ["cli"] }
