name: 🦀 publish rust crate

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🦀 Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 📥  Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: 📥  Install js dependencies
        run: |
          npm install yarn
          npm install tree-sitter-cli -g

      - name: 🌲 Generate the parser
        run: tree-sitter generate

      - name: 🛠 Build rust bindings
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      # Run the tests
      - name: 🧪 Now run the rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
