on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: 🦀  Build and Test rust bindings

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      
      - name: 📥 Download the repository
        uses: actions/checkout@v2
      - name: 🦀 Install rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 📥  Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: 📥  Install js dependencies
        run: |
          npm install yarn
          npm install tree-sitter-cli -g
          yarn

      - name: 🌲 Generate the parser
        run: tree-sitter generate

      - name: 🛠 Build rust bindings
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      # Run the tests
      - name: 🧪 Now run the rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test